### ISSUE TITLE
Gradle nicht gefunden

### ISSUE THREAD

**Issue by benCoder01** [Skn0tt/nrwDatenStrukturenTests#3]
folgender fehler tritt auf:

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

der ist jetzt hier auf Linux, auf Windows habe ich das noch nicht ausprobiert.

**Comment by Skn0tt** [comment]
Mit welcher Version tritt das auf? Clone' bitte nochmal und probier es noch einmal, vielleicht geht es dann.

**Comment by benCoder01** [comment]
ich habe das repo noch einmal gecloned, es funktioniert aber immer noch nicht, und der Fehler tritt immer noch auf.

**Comment by Skn0tt** [comment]
Sollte durch https://github.com/Skn0tt/nrwDatenStrukturenTests/commit/633925b289dd30b220a373ab8023da4e6b6e0841 gefixed sein. Überprüfst du das noch einmal?

**Comment by benCoder01** [comment]
perfekt...funktioniert jetzt

**Comment by Skn0tt** [comment]
Super 👍 
Problem war, dass `gradle-wrapper.jar` im LFS ist. Dadurch wird beim Clonen/Download als ZIP nur der Pointer-File gedownloadet, der dann natürlich auch keine Main-Klasse hat....
Datei ist jetzt nicht mehr im LFS, das hat den Fehler gefixed 😄
